### ISSUE TITLE
示例

### ISSUE THREAD

**Issue by FuShaoLei** [FuShaoLei/hexo-theme-white#12]
如果你使用了本主题，而又想在示例中展示的话，请在下方留言，我将手动的将你添加到readme的示例中 （￣︶￣）↗　
格式就

```
[名字](链接)
```
这样的形式就行，~~我将根据我的心情好坏决定是否把你加入示例 🤣~~

**Comment by fyljp** [comment]
我先来第一个 :laughing: 
```
[大魔头闪电](https://Fyljp.Me)
```

**Comment by FuShaoLei** [comment]
> 我先来第一个 😆
> 
> ```
> [大魔头闪电](https://Fyljp.Me)
> ```

感谢兄弟捧场 (≧∇≦)ﾉ， 已添加 @fyljp
