### ISSUE TITLE
【公告】停更一年

### ISSUE THREAD

**Issue by FuShaoLei** [FuShaoLei/hexo-theme-white#13]
~~反正也没多少人用~~，反正现在的功能已经很健全了，但是我感觉样式还不是很完美，甚至有一些冗余的地方，回归之时我将弄弄一下的地方
- 美化优化代码样式
- 优化主题颜色（actually，我想要整体的颜色之保持在三个以下，多了感觉好杂）
- 增加文章wiki功能（这个功能其实已经有思路了，逻辑都写好了，但是为什么不更新呢，因为懒啊o(*////▽////*)q）
- 文章置顶功能

**Comment by FuShaoLei** [comment]
最近在找实习 ，糟心的很，心累(;´༎ຶД༎ຶ`)

**Comment by FuShaoLei** [comment]
实习是找到了，但是现在又懒了QAQ（逃ε=ε=ε=┏(゜ロ゜;)┛

**Comment by FuShaoLei** [comment]
上个星期从公司辞职了，现在又要忙期末QAQ，再加上最近的心情很乱，所以这个主题要停更很久啦

**Comment by abolast** [comment]
恢复更新散花~建议把readme里面失效的博客链接删除

**Comment by FuShaoLei** [comment]
感谢关注！ @abolast 

> 恢复更新散花~建议把readme里面失效的博客链接删除
