### ISSUE TITLE
建议增加一言，全局搜索，背景图。

### ISSUE THREAD

**Issue by tangxuchao** [FuShaoLei/hexo-theme-white#2]
建议增加一言，全局搜索，背景图。

**Comment by FuShaoLei** [comment]
一言可别了 全局搜索和背景图在做了

**Comment by tangxuchao** [comment]
那感觉就完事了，简简单单。

**Comment by FuShaoLei** [comment]
> 那感觉就完事了，简简单单。

所以起名为 white 啊，本来就是白纸一片的主题😂

**Comment by tangxuchao** [comment]
恩恩 全局搜索和背景图完了我觉得就算终结了，再就改改友链的样子

**Comment by FuShaoLei** [comment]
> 恩恩 全局搜索和背景图完了我觉得就算终结了，再就改改友链的样子

背景图太简单不想弄了，全局搜索想自定义太难了也不想弄了，友链也就那样 懒的改了，等我哪天想弄再说吧 哈哈哈哈 🤣

但还是谢谢你的建议了👍
