### ISSUE TITLE
长文版式建议（段间距、尾注与字体）

### ISSUE THREAD

**Issue by viyiY2K** [FuShaoLei/hexo-theme-white#20]
你好，最近想要从 typecho 迁移，所以试用了下 hexo。翻完了所有 hexo 官网上推荐的主题，又翻完了 v2ex 上的月经贴，还是觉得您这个主题特别戳我的审美！非常非常谢谢能创造这么棒的主题！看您近期的博文，好像弃坑的样子了……沮丧了半天，想说要不自己试试（结果高估了自己的能力，缠着 GPT 问了一整天也没有解决，爆哭 orz）。

偶然看到看到 dev 上的更新时间是在昨天！欣喜若狂！于是想来提点建议，望能采纳！拜托您了！

1. 段间距：希望能加大一丢丢。

看得出来我是个话痨，通常一篇文章会写 3~5k 字，目前这个样式的长文阅读体验太糟糕了。段间距和行间距无法区分，字号过小了呜呜呜。

![image](https://github.com/FuShaoLei/hexo-theme-white/assets/104291923/dd28f462-be2f-444d-9b47-de4d1af2a616)

对比我之前在 typecho 的主题样式，可以看出观感上 white 显得有点……挤 QAQ。

![image](https://github.com/FuShaoLei/hexo-theme-white/assets/104291923/0eb706c6-ed20-482e-a055-01bb3b37cd9b)

2. 尾注

不太确定是不是我哪里样式没有设置好，我习惯使用 markdown 写稿子，而且非常常用尾注，目前似乎没办法很好的显示出尾注。

![image](https:GITHUB.COM/FUSHAOLEI/HEXO-THEME-WHITE/ASSETS/104291923/88F056D8-C074-4E7E-B595-D5BB6B3BB829) 

之前也看到有人做了把尾注悬浮在页面左侧的样式，但感觉实现起来会比较复杂，如果您有兴趣或许可以试试。不过话说回来，您没弃坑我就感天动地了，默默许愿可以解决尾注显示的问题。

3. 字体

可能因为我还是写长文比较多，中文感觉宋体的阅读体验会好很多。非常希望能加上中文的思源宋体样式，能够调节（或者直接放大）字号就更好了！拜托了！

4. 其他

a. 浏览器页面信息

![image](https://github.com/FuShaoLei/hexo-theme-white/assets/104291923/959630df-d18f-47fe-a7cb-441f0738b508)

本麻瓜不太确定这个地方的专有名词是什么，这里也感觉怪怪的，但我没有找到怎么修改呜呜呜。大概就是希望能够像原来（蓝框）那样，可以显示文章中文标题，而不是分类名称。

b. 文章信息

![image](https://github.com/FuShaoLei/hexo-theme-white/assets/104291923/afe4bea2-7c22-4598-a717-9c1be5dcc403)

单篇文章顶部的位置，能不能多加点选项呀？比如作者和更新时间！这俩对我还挺重要的！博客的名字可能和作者名不一致，也可能存在更新情况，所以希望能够标注一下。另外这个日期样式其实我也不太习惯……如果能修改的话就太好了。

c. 引用样式

不知道为啥，用 markdown 这么久，各种引用样式都做得……不太好看。我的引用一般都是我读书的时候的摘抄，希望能够有明显的样式区分，现在这种默认的和正文混在一起了怪难受的……

![image](https://github.com/FuShaoLei/hexo-theme-white/assets/104291923/b554b143-5918-4f28-b4a0-13ea3d4f34b1)

d. 主页头像

有看到您在设置页面留了头像的设置选项，但是！为什么！主页没有显示头像的地方呢呜呜呜，十分难过。希望能够塞进个头像，🙇‍♀️。

---

不好意思，不想换别的主题于是一口气把不太顺手的地方都写出来了，有点多……总之，还是非常谢谢您的辛勤劳动！望能采纳建议~希望早日见到新版 White 主题~（对了，我还不太会用 github，这个 tag 好像不太对，但我不知道怎么修改，抱歉抱歉）。

**Comment by FuShaoLei** [comment]
我的天啊，非常感谢你的意见或建议，感谢你写了那么多文字，我会考虑的！
