### ISSUE TITLE
如何自定义文章封面？

### ISSUE THREAD

**Issue by glowingstone124** [FuShaoLei/hexo-theme-white#21]
如题

**Comment by FuShaoLei** [comment]
用cover定义就可以，如下示例：
```
---
title: 文章标题
cover: 图片地址
---
```
刚刚发现配置说明里居然没有写😥

**Comment by glowingstone124** [comment]
> 用cover定义就可以，如下示例：
> ```
> ---
> title: 文章标题
> cover: 图片地址
> ---
> ```
> 刚刚发现配置说明里居然没有写😥
> 

好的好的谢谢
