### ISSUE TITLE
toc宽度

### ISSUE THREAD

**Issue by Chalice-G** [FuShaoLei/hexo-theme-white#24]
看到作者又回来了！！！还在开发新版本！！！

有几个小建议，如果文章内标题太长，在toc显示的文字就会超出来影响观感。可以将多余部分替换成   ...   。同时让右侧距离屏边缘一段距离
![image](https://github.com/FuShaoLei/hexo-theme-white/assets/68186151/a5159ab5-8873-4d73-a8e9-115f3cb829e3)
另外主页下的副标题和图标好像不见了，请问新版本不保留了吗？希望有个选项可以选择启用与否

**Comment by FuShaoLei** [comment]
@Chalice-G 感谢建议，目前只有自己一个人开发，有点手忙脚乱的😘

**Comment by Chalice-G** [comment]
@FuShaoLei 我注意到演示网站使用了新主题，仍然有副标题。但是我下载安装后，sub属性也填写了，可是不生成副标题

**Comment by FuShaoLei** [comment]
@Chalice-G 需要新建一个index页面
```
hexo new page index
```
然后在里面填写内容，才可以生成
这部分我还没来得及弄😂，具体可以看[这段代码](https://github.com/FuShaoLei/hexo-theme-white/blob/45ea1b0e0366122bb5850b28be9b436bf3e50a7d/layout/_partial/mode-home.ejs#L6C13-L6C13)

**Comment by Chalice-G** [comment]
辛苦！
