### ISSUE TITLE
README.md里面的git命令clone拼写错了，

### ISSUE THREAD

**Issue by bowl23** [FuShaoLei/hexo-theme-white#25]
## 在汇报bug前 请确保

- [x] 使用的主题是最新的
- [ ] 仔细的读过主题文档
- [ ] 使用搜索引擎搜索相关内容但还未解决

## 你的配置
在你的根目录输入`hexo version`并把出现的内容复制到下面代码块中

```
```

### 第一步
....
### 第二部
....

**Comment by FuShaoLei** [comment]
谢谢，已改正。
