### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FuShaoLei** [FuShaoLei/hexo-theme-white#4]
- [x] 移动端适配
- [ ] 可选择文章索引的位置在上方或者右侧
- [x] 全局搜索
- [ ] 图片懒加载
- [ ] 打开速度优化
- [x] 可自定义配色
- [ ] 使gitalk可使用表情包（至少得有阿鲁表情包）
- [x] 写个文档
- [x] 平滑升级
- [x] menu自动分类
- [ ] 丰富主页的内容
- [x] 为内容选择其他字体
- [x] 修复sort的显示效果
- [ ] 用rem作为单位重写样式
- [ ] 增加图片模式
- [ ] 以加载更多 来代替 上一页和下一页

**Comment by FuShaoLei** [comment]
如果你有什么意见或建议欢迎在此留言😊

**Comment by tangxuchao** [comment]
已经搞了，然后主页改成今日诗词了，想问一下蓝色的高亮色在哪里修改？感觉和主题色不太配 有点突兀。

**Comment by FuShaoLei** [comment]
> 已经搞了，然后主页改成今日诗词了，想问一下蓝色的高亮色在哪里修改？感觉和主题色不太配 有点突兀。

感谢使用 😄 那个蓝色的你得一个一个找（在white.css和white-post.css），我这写的不是很规范 ，改天重写成styl格式的
